include ../build/common/CommonDefs.mak

BIN_DIR = ../bin

INC_DIRS = /usr/local/include/ni /usr/include/ni

SRC_FILES = ./*.cpp

EXE_NAME = 01-depth-test
USED_LIBS = OpenNI

include ../build/common/CommonCppMakefile
